version: '3.8'

services:
  app:
    build: .
    container_name: rails_app
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ".:/src/app"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_URL=postgres://postgres:password@db:5432/myapp_development
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
    stdin_open: true
    tty: true
    command: >
      sh -c "bin/rails db:prepare && bin/rails server -b 0.0.0.0"

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sidekiq:
    build: .
    container_name: sidekiq_worker
    depends_on:
      - app
      - redis
    volumes:
      - ".:/src/app"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/myapp_development
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
    command: ["bundle", "exec", "sidekiq"]

volumes:
  postgres_data:
  redis_data:
